# Use the official Debian image as the base
FROM python:3.12

# Update package index and install dependencies
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    openjdk-17-jdk \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the entire project into the container
COPY . .

# Install Python dependencies with --break-system-packages flag
RUN pip3 install --break-system-packages poetry

RUN poetry install

# Set the default command to run main.py
CMD ["poetry", "run", "python3", "main.py"]
