[tool.poetry]
name = "digesto-hybrid-search"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
simple-term-menu = "^1.6.4"
tqdm = "^4.66.5"
sentence-transformers = "^3.0.1"
pymupdf = "^1.24.9"
nltk = "3.8.1" # Updating it causes an error with Punkt
python-terrier = {git = "https://github.com/terrier-org/pyterrier.git", rev = "master"}
logging = "^0.4.9.6"
pypdf = "^4.3.1"
faiss-cpu = "^1.8.0.post1"
tabulate = "^0.9.0"
python-dotenv = "^1.0.1"
dotenv = "^0.9.9"
numpy = "^2.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

